# Generated by Django 6.0 on 2026-01-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scanhistory_scanfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanfinding',
            name='action_taken',
            field=models.CharField(default='flagged', max_length=20),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='endpoint_sensitivity',
            field=models.CharField(default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='priority_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('target_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source_ip', 'timestamp'], name='api_request_source__62802a_idx')],
            },
        ),
    ]
