# Generated by Django 6.0 on 2026-01-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scanfinding_action_taken_scanfinding_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanfinding',
            name='remediation_simple',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='remediation_technical',
            field=models.TextField(blank=True, default=''),
        ),
    ]
