# Generated by Django 6.0 on 2026-01-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scanfinding_remediation_simple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanfinding',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='scanfinding',
            name='confidence',
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='classification',
            field=models.CharField(choices=[('confirmed', 'Confirmed Vulnerability'), ('likely', 'Likely Vulnerability'), ('suspicious', 'Suspicious Pattern'), ('informational', 'Informational')], default='suspicious', max_length=20),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='context_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='exploit_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='pattern_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='response_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='total_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('partial', 'Partially Validated'), ('failed', 'Not Validated')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ScannerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_positives', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('false_negatives', models.IntegerField(default=0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('benchmark_source', models.CharField(blank=True, default='', max_length=100)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.scanhistory')),
            ],
        ),
    ]
