# Generated by Django 6.0 on 2026-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_scanfinding_action_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanfinding',
            name='explanation_simple',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='explanation_technical',
            field=models.TextField(blank=True, default=''),
        ),
    ]
