# Generated by Django 6.0 on 2026-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_ai_explanation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanfinding',
            name='ai_classification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='class_probabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='detection_method',
            field=models.CharField(choices=[('rule', 'Rule-Based'), ('ai', 'AI-Classified'), ('hybrid', 'Hybrid')], default='rule', max_length=20),
        ),
    ]
