# Generated by Django 6.0 on 2026-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_scanfinding_ai_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanfinding',
            name='code_fix',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='code_framework',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='code_language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='evidence_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='fix_references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='forensic_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='requires_immediate_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='triage_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
