# Generated by Django 6.0 on 2026-02-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_ai_priority_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hash', models.CharField(db_index=True, max_length=64)),
                ('endpoint', models.TextField()),
                ('parameter', models.CharField(max_length=255)),
                ('vuln_type', models.CharField(max_length=50)),
                ('framework', models.CharField(blank=True, max_length=100, null=True)),
                ('payload_used', models.TextField()),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Discovery Memories',
                'ordering': ['-created_at'],
            },
        ),
    ]
