# Generated by Django 6.0 on 2026-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_discoverymemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='current_step',
            field=models.CharField(default='Initializing...', max_length=255),
        ),
    ]
