# Generated by Django 4.2.11 on 2026-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_scanhistory_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='worker_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
