# Generated by Django 6.0 on 2026-03-05 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_scanhistory_last_heartbeat_scanhistory_worker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
